### ISSUE TITLE
This service is not ready to serve traffic. If you are the site owner, please check that your service is passing health checks.

### ISSUE THREAD

**Issue by zknb-666** [V-Official-233/AList-Aria2-Render#1]
This service is not ready to serve traffic. If you are the site owner, please check that your service is passing health checks.
每次出现这个都要重新部署

**Comment by V-Official-233** [comment]
在修力，现在时间不是很多，非常抱歉哈

**Comment by thincen** [comment]
不知道render是不是更新了什么, 以前我自己的web server用的好好的, 现在也出现这个情况。15min休眠, 然后健康检查不通过, 重启下(就是重新设置下健康检查的path)又没问题了

**Comment by thincen** [comment]
官方让重新部署
Elevated errors on deployed free services
Resolved -  This incident has been resolved. Services affected by this error may still require a redeploy. 
May 11, 22:37 UTC
Monitoring -  We have applied a fix and are monitoring the results. Users who are still seeing this error should re-deploy any affected services. 
May 11, 19:50 UTC
Investigating -  We're continuing to investigate an issue causing errors when accessing free Web Services. Users may see "This service is not ready to serve traffic. If you are the site owner, please check that your service is passing health checks."

**Comment by zknb-666** [comment]
Thinks
