### ISSUE TITLE
为何我这部署失败呢

### ISSUE THREAD

**Issue by GD2021** [V-Official-233/AList-Aria2-Render#3]
![image](https://github.com/V-Official-233/AList-Aria2-Render/assets/81171294/6d6f9478-25e8-4478-985a-ea5677f5a97c)
![image](https://github.com/V-Official-233/AList-Aria2-Render/assets/81171294/465d6976-853a-46eb-bcaf-cd8b41f7b771)

**Comment by V-Official-233** [comment]
死循环阅读配置文件，你接数据库了？

**Comment by GD2021** [comment]
接了啊

**Comment by V-Official-233** [comment]
我又试了一下，我这边没有这个问题，不管是新开一个，还是之前接入数据库的旧的都没有这个问题
